/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.7/samples
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
	application
	id("se.patrikerdes.use-latest-versions") version "0.2.18"
	id("com.github.ben-manes.versions") version "0.51.0"
}

dependencies {
	implementation("org.apache.commons:commons-lang3:3.14.0")
}

repositories {
	mavenCentral()
}

application {
	mainClass.set("io.hexlet.example.App")
}
